Repository livable-final/client, pull requests merged in 2023-10, with the labels that each got.

#148 feat: 구내식당/도시락 리뷰 작성 및 포인트 지급 api 연결, 플로우 구현
  public/point/coin.webp
  src/assets/images/index.ts
  src/components/lunch/LunchSubTitle.tsx
  src/components/lunch/calendar/LunchCalendarBottomSheet.tsx
  src/components/lunch/calendar/LunchCalendarCafeteria.tsx
  src/components/lunch/calendar/LunchCalendarEatOut.tsx
  src/components/lunch/calendar/LunchCalendarLunchBox.tsx
  src/components/lunch/calendar/LunchCalendarMenu.tsx
  src/components/lunch/calendar/LunchCalendarPointInform.tsx
  src/components/lunch/calendar/LunchCalendarReview.tsx
  src/components/lunch/calendar/LunchCalendarSearch.tsx
  src/pages/lunch/point.tsx
  src/types/lunch/calendar.ts
  tsconfig.json
Labels: 💎 완료

#151 feat: 플로팅 버튼 구현 및 useFetch 수정
  next.config.js
  src/assets/icons/Popup.svg
  src/assets/icons/PopupActive.svg
  src/assets/icons/Write.svg
  src/assets/icons/index.ts
  src/components/common/ToWrite.tsx
  src/components/common/Toggle.tsx
  src/components/lunch/detail/LunchDetailContents.tsx
  src/components/lunch/detail/index.tsx
  src/components/lunch/ranking/LunchRankingReviews.tsx
  src/components/lunch/review/LunchReviews.tsx
  src/components/lunch/review/LunchReviewsByRanking.tsx
  src/hooks/useFetch.ts
  src/pages/api/lunch/lunchRequests.ts
  src/pages/lunch/index.tsx
  src/stores/useBuildingStore.ts
  src/stores/useSaveStore.ts
  src/types/common/response.ts
  src/types/lunch/api.ts
Labels: 💎 완료

#153 feat: Alert 추가
  src/assets/icons/Error.svg
  src/assets/icons/Popup.svg
  src/components/common/Alert.tsx
  src/components/common/Icons.tsx
  src/components/invitation/view/InvitaitionCarousel.tsx
  src/components/lunch/roulette/LunchRoulettePopup.tsx
  src/constants/common/index.ts
  src/pages/lunch/roulette.tsx
  src/stores/useAlertStore.ts
  src/stores/useRouletteStore.ts
  src/styles/theme.ts
  src/types/common/alert.ts
Labels: 💅 디자인

#154 feat:초대 목록 관련 api 연결
  package-lock.json
  src/assets/icons/ErrorIcon.svg
  src/assets/icons/index.ts
  src/components/invitation/InvitationViewForm.tsx
  src/components/invitation/edit/InvitationAddVisitorList.tsx
  src/components/invitation/edit/InvitationEdit.tsx
  src/components/invitation/view/InvitationHostInfo.tsx
  src/components/invitation/view/InvitationInfoContainer.tsx
  src/components/user/UserInvitationList.tsx
  src/components/user/UserInvitationListEdit.tsx
  src/components/user/UserInvitationListItem.tsx
  src/pages/api/invitation/editRequests.ts
  src/pages/invitation/edit.tsx
  src/stores/useInvitationEditStore.ts
  src/types/invitation/api.ts
  src/types/invitation/edit.ts
  src/types/invitation/view.ts
  src/utils/createHyphenDate.ts
Labels: 💎 완료

#155 feat: 예외처리, Alert 노출 추가, 예약 가능 시간 API 1차 연결 완료
  src/assets/icons/Exit=small.svg
  src/components/common/AddressBook.tsx
  src/components/common/Alert.tsx
  src/components/common/Icons.tsx
  src/components/common/Modal.tsx
  src/components/common/NameTag.tsx
  src/components/common/TimeSelector.tsx
  src/components/invitation/create/InvitationDateTime.tsx
  src/components/invitation/create/InvitationInfo.tsx
  src/components/invitation/create/InvitationPlace.tsx
  src/components/invitation/create/InvitationSelectTime.tsx
  src/components/invitation/create/InvitationVisitorsContainer.tsx
  src/components/invitation/edit/InvitationAddVisitorList.tsx
  src/constants/common/index.ts
  src/pages/api/invitation/createRequests.ts
  src/stores/useAlertStore.ts
  src/stores/useInvitationCreateStore.ts
  src/types/invitation/api.ts
  src/utils/getFormatDate.ts
Labels: 💎 완료, 🛠 기능

#157 feat: 포인트 지도 구현 및 페이지 이동 추가, 맛있오 버튼 스타일 변경
  src/assets/icons/DateDishNoPhoto.svg
  src/assets/icons/index.ts
  src/assets/icons/point10.svg
  src/assets/icons/point1000.svg
  src/assets/icons/point10pink.svg
  src/assets/icons/point1500.svg
  src/assets/icons/point500.svg
  src/assets/icons/present.1500.svg
  src/assets/icons/present.svg
  src/assets/icons/present1000.svg
  src/assets/icons/present500.svg
  src/components/common/Header.tsx
  src/components/lunch/calendar/LunchCalendarCafeteria.tsx
  src/components/lunch/calendar/LunchCalendarEatOut.tsx
  src/components/lunch/calendar/LunchCalendarLunchBox.tsx
  src/components/lunch/calendar/LunchCalendarPointCard.tsx
  src/components/lunch/calendar/LunchCalendarPointInform.tsx
  src/components/lunch/calendar/LunchCalendarRatingBtn.tsx
  src/components/lunch/calendar/LunchCalendarReview.tsx
  src/constants/common/pages.ts
  src/constants/lunch/index.ts
  src/stores/useSaveStore.ts
  src/stores/useWriteStore.ts
  src/types/common/header.ts
Labels: 💎 완료, 🛠 기능, 💅 디자인

#159 feat:수정 api 연결, 방문 목적 한/영 변환 유틸 함수 생성
  src/components/invitation/edit/InvitationAddVisitorList.tsx
  src/components/invitation/edit/InvitationEdit.tsx
  src/components/user/UserInvitationListItem.tsx
  src/pages/api/invitation/editRequests.ts
  src/stores/useInvitationEditStore.ts
  src/types/invitation/api.ts
  src/types/invitation/edit.ts
  src/utils/changeVisitPurpose.ts
Labels: 💎 완료

#162 feat: 응답데이터 코드 수정
  src/assets/icons/DateDishNoPhoto.svg
  src/components/lunch/calendar/LunchCalendarMenu.tsx
  src/components/lunch/calendar/LunchCalendarPointCard.tsx
  src/components/lunch/calendar/LunchCalendarRatingBtn.tsx
  src/components/lunch/calendar/LunchCalendarSearch.tsx
  src/types/lunch/calendar.ts
Labels: 📖 문서 수정

#164 feat: 포인트 지도 컴포넌트 변경
  src/pages/lunch/point.tsx
Labels: 📖 문서 수정

#165 fix: 오늘 점심 디자인 수정 및 룰렛 기능 업데이트
  src/assets/icons/BottomArrow.svg
  src/assets/icons/Home.svg
  src/assets/icons/HomeActive.svg
  src/assets/icons/Lunch.svg
  src/assets/icons/LunchActive.svg
  src/assets/icons/MyActive.svg
  src/assets/icons/index.ts
  src/components/common/Bnb.tsx
  src/components/common/Icons.tsx
  src/components/common/Title.tsx
  src/components/common/ToTop.tsx
  src/components/common/ToWrite.tsx
  src/components/lunch/LunchRest.tsx
  src/components/lunch/LunchRoulette.tsx
  src/components/lunch/detail/LunchDetailContents.tsx
  src/components/lunch/detail/index.tsx
  src/components/lunch/ranking/LunchRankingPodium.tsx
  src/components/lunch/ranking/LunchRankingReviews.tsx
  src/components/lunch/ranking/index.tsx
  src/components/lunch/review/LunchReviews.tsx
  src/components/lunch/review/LunchReviewsByRest.tsx
  src/components/lunch/roulette/LunchRouletteLockBtn.tsx
  src/components/lunch/roulette/LunchRoulettePopup.tsx
  src/components/lunch/roulette/LunchRoulettePushBtn.tsx
  src/constants/common/index.ts
  src/constants/home/homeTexts.ts
  src/constants/lunch/index.ts
  src/hooks/useIsScrollYTop.ts
  src/pages/api/lunch/lunchRequests.ts
  src/pages/lunch/roulette.tsx
  src/styles/theme.ts
  src/types/common/response.ts
  src/types/lunch/api.ts
  src/types/lunch/ranking.ts
  src/types/lunch/reviewList.ts
  src/types/lunch/roulette.ts
  src/utils/getWeatherIcon.ts
  src/utils/selectRandomItem.ts
Labels: 💎 완료

#169 feat: 초대장 qr Api 연동
  public/defaultImage.jpg
  src/assets/defaultImage.jpg
  src/assets/icons/InfoBuliding.svg
  src/assets/icons/InfoCategory.svg
  src/assets/icons/InfoHost.svg
  src/assets/icons/InfoParking.svg
  src/assets/icons/InfoPlace.svg
  src/assets/icons/index.ts
  src/components/common/Icons.tsx
  src/components/invitation/InvitationViewForm.tsx
  src/components/invitation/view/InvitaitionCarousel.tsx
  src/components/invitation/view/InvitationHostInfo.tsx
  src/components/invitation/view/InvitationInfo.tsx
  src/components/invitation/view/InvitationInfoCategory.tsx
  src/components/invitation/view/InvitationInfoContainer.tsx
  src/components/invitation/view/InvitationQrInfo.tsx
  src/components/invitation/view/InvitationQrInfoCode.tsx
  src/components/invitation/view/InvitationQrInfoText.tsx
  src/constants/common/index.ts
  src/constants/invitation/viewTexts.ts
  src/pages/api/axios.ts
  src/pages/api/invitation/viewRequests.ts
  src/types/invitation/api.ts
  src/types/invitation/view.ts
Labels: 💎 완료, 🛠 기능, 💅 디자인

#172 feat: 초대장 저장 API 연결
  .eslintrc.json
  src/components/common/TimeSelector.tsx
  src/components/common/Toggle.tsx
  src/components/invitation/create/InvitationDateTime.tsx
  src/components/invitation/create/InvitationDoneMessage.tsx
  src/components/invitation/create/InvitationInfo.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/components/invitation/create/InvitationPurposeContainer.tsx
  src/components/invitation/create/InvitationSelectTime.tsx
  src/components/invitation/create/InvitationVisitorsContainer.tsx
  src/pages/api/invitation/createRequests.ts
  src/stores/useInvitationCreateStore.ts
  src/stores/useTimeSelectorStore.ts
  src/stores/useToggleStore.ts
  src/styles/theme.ts
  src/types/common/toggle.ts
  src/types/invitation/api.ts
  src/types/invitation/create.ts
  src/utils/createTimeSlot.ts
  src/utils/createTimeSlots.ts
  src/utils/getCommonTimeList.ts
  src/utils/getFormatDate.ts
  src/utils/parseDate.ts
Labels: 💎 완료, 🛠 기능

#174 feat: 방문증 테마 커스텀 기능 구현
  src/assets/icons/InfoBuliding.svg
  src/assets/icons/InfoHost.svg
  src/assets/icons/InfoParking.svg
  src/assets/icons/InfoPlace.svg
  src/components/invitation/view/InvitationInfo.tsx
  src/components/invitation/view/InvitationInfoCategory.tsx
  src/components/invitation/view/InvitationQrInfo.tsx
  src/components/invitation/view/InvitationQrInfoText.tsx
  src/constants/invitation/viewTexts.ts
  src/stores/useThemeStore.ts
  src/types/invitation/view.ts
Labels: 💎 완료, 🛠 기능, 💅 디자인

#177 fix: 리뷰 등록 에러 해결
  src/components/lunch/calendar/LunchCalendarBottomSheet.tsx
  src/components/lunch/calendar/LunchCalendarCafeteria.tsx
  src/components/lunch/calendar/LunchCalendarDate.tsx
  src/components/lunch/calendar/LunchCalendarDateContent.tsx
  src/components/lunch/calendar/LunchCalendarEatOut.tsx
  src/components/lunch/calendar/LunchCalendarLunchBox.tsx
  src/components/lunch/calendar/LunchCalendarPointCard.tsx
  src/components/lunch/calendar/LunchCalendarPointInform.tsx
  src/components/lunch/calendar/LunchCalendarReview.tsx
  src/components/lunch/calendar/LunchCalendarSelectBtn.tsx
Labels: 🐞 버그, 💎 완료

#179 refactor: 오늘 점심 리팩토링 및 룰렛 가동 전 식당 추천 기능 추가
  next.config.js
  src/assets/icons/Popup.svg
  src/assets/icons/PopupActive.svg
  src/assets/icons/index.ts
  src/components/common/Alert.tsx
  src/components/common/Icons.tsx
  src/components/home/reception/index.tsx
  src/components/lunch/LunchCard.tsx
  src/components/lunch/LunchMainContents.tsx
  src/components/lunch/LunchRest.tsx
  src/components/lunch/LunchRoulette.tsx
  src/components/lunch/calendar/LunchCalendarCafeteria.tsx
  src/components/lunch/detail/LunchDetailContents.tsx
  src/components/lunch/detail/index.tsx
  src/components/lunch/ranking/LunchRankingPodium.tsx
  src/components/lunch/ranking/LunchRankingReviews.tsx
  src/components/lunch/ranking/LunchRankings.tsx
  src/components/lunch/ranking/index.tsx
  src/components/lunch/review/LunchReview.tsx
  src/components/lunch/review/LunchReviewPhotos.tsx
  src/components/lunch/review/LunchReviewRatings.tsx
  src/components/lunch/review/LunchReviews.tsx
  src/components/lunch/review/LunchReviewsByRanking.tsx
  src/components/lunch/review/LunchReviewsByRest.tsx
  src/components/lunch/roulette/LunchRouletteBg.tsx
  src/components/lunch/roulette/LunchRouletteLockBtn.tsx
  src/components/lunch/roulette/LunchRoulettePopup.tsx
  src/components/lunch/roulette/LunchRoulettePushBtn.tsx
  src/components/user/UserInfo.tsx
  src/constants/common/index.ts
  src/constants/lunch/index.ts
  src/hooks/useFetch.ts
  src/pages/_app.tsx
  src/pages/api/lunch/lunchRequests.ts
  src/pages/index.tsx
  src/pages/lunch/roulette.tsx
  src/stores/useRouletteStore.ts
  src/stores/useUserStore.ts
  src/styles/theme.ts
  src/types/common/response.ts
  src/types/lunch/api.ts
Labels: 💎 완료

#183 refactor: 오늘 리뷰 등록 체크 및 기타 수정
  src/assets/icons/index.ts
  src/components/lunch/calendar/LunchCalendarCafeteria.tsx
  src/components/lunch/calendar/LunchCalendarEatOut.tsx
  src/components/lunch/calendar/LunchCalendarForm.tsx
  src/components/lunch/calendar/LunchCalendarLunchBox.tsx
  src/components/lunch/calendar/LunchCalendarMain.tsx
  src/pages/api/lunch/calendarRequests.ts
Labels: 📖 문서 수정, 💎 완료

#192 fix: QA 수정사항 반영 (타이틀 스토어 초기화 외 디자인 요소 수정)
  src/components/common/Category.tsx
  src/components/invitation/create/InvitationDateTime.tsx
  src/components/invitation/create/InvitationPurposeContainer.tsx
  src/stores/useInvitationCreateStore.ts
Labels: 🐞 버그, 💎 완료, 💅 디자인

#194 Refactor: 최근 검색 내역 기능 추가 및 스타일 수정
  src/components/lunch/LunchSubTitle.tsx
  src/components/lunch/calendar/LunchCalendarForm.tsx
  src/components/lunch/calendar/LunchCalendarListItem.tsx
  src/components/lunch/calendar/LunchCalendarMain.tsx
  src/components/lunch/calendar/LunchCalendarPointCard.tsx
  src/components/lunch/calendar/LunchCalendarSearch.tsx
  src/components/lunch/calendar/LunchCalendarWriteBtn.tsx
  src/stores/useSaveStore.ts
  src/types/lunch/calendar.ts
Labels: 🔧 진행중, 🛠 기능, 💅 디자인

#195 fix: 방문자 추가 컴포넌트 에러 핸들링 및 방문자 초대 플로우 반응형/아이콘 등 수정
  src/assets/icons/LocationLine.svg
  src/assets/icons/index.ts
  src/components/common/Category.tsx
  src/components/common/CheckBox.tsx
  src/components/common/Input.tsx
  src/components/invitation/create/InvitationInfo.tsx
  src/components/invitation/create/InvitationPurposeContainer.tsx
  src/components/invitation/create/InvitationVisitorsContainer.tsx
  src/components/invitation/create/InvitationVisitorsList.tsx
  src/components/invitation/edit/InvitationAddVisitorList.tsx
Labels: 🐞 버그, 💎 완료, 💅 디자인

#197 feat: 초대장 수정하기 재전송 모달, 전송 완료 페이지 추가 및 svg 아이콘 클릭 수정
  src/components/invitation/InvitaitonEditForm.tsx
  src/components/invitation/create/InvitationDoneMessage.tsx
  src/components/invitation/edit/InvitationAddVisitorList.tsx
  src/components/invitation/edit/InvitationEdit.tsx
  src/components/invitation/view/InvitationInfoCategory.tsx
  src/components/user/UserInvitationList.tsx
  src/components/user/UserInvitationListEdit.tsx
  src/constants/invitation/editTexts.ts
  src/pages/invitation/edit.tsx
Labels: 🐞 버그, 💎 완료, 🛠 기능, 💅 디자인

#201 Refactor/196 qa
  src/components/common/Header.tsx
  src/components/common/Input.tsx
  src/components/lunch/calendar/LunchCalendarBottomSheet.tsx
  src/components/lunch/calendar/LunchCalendarCafeteria.tsx
  src/components/lunch/calendar/LunchCalendarDateContent.tsx
  src/components/lunch/calendar/LunchCalendarDetailsSlide.tsx
  src/components/lunch/calendar/LunchCalendarEatOut.tsx
  src/components/lunch/calendar/LunchCalendarForm.tsx
  src/components/lunch/calendar/LunchCalendarListItem.tsx
  src/components/lunch/calendar/LunchCalendarLunchBox.tsx
  src/components/lunch/calendar/LunchCalendarMain.tsx
  src/components/lunch/calendar/LunchCalendarPhoto.tsx
  src/components/lunch/calendar/LunchCalendarRatingBtn.tsx
  src/components/lunch/calendar/LunchCalendarReview.tsx
  src/components/lunch/calendar/LunchCalendarReviewCategory.tsx
  src/components/lunch/calendar/LunchCalendarWriteBtn.tsx
  src/types/common/input.ts
Labels: 💎 완료

#203 refactor: 코인 애니메이션 추가 구현 및 폰트 수정
  src/assets/fonts/YeongdeokBlueroad.ttf
  src/assets/icons/Clock.svg
  src/components/lunch/calendar/LunchCalendarListItem.tsx
  src/components/lunch/calendar/LunchCalendarPointInform.tsx
  src/styles/font.ts
  src/styles/theme.ts
Labels: 📖 문서 수정

#204 refactor: 맛 평가 버튼 스타일 및 submit 버튼 disabled 추가
  src/components/lunch/calendar/LunchCalendarCafeteria.tsx
  src/components/lunch/calendar/LunchCalendarDateContent.tsx
  src/components/lunch/calendar/LunchCalendarEatOut.tsx
  src/components/lunch/calendar/LunchCalendarLunchBox.tsx
  src/components/lunch/calendar/LunchCalendarRatingBtn.tsx
  src/components/lunch/calendar/LunchCalendarReviewCategory.tsx
  src/types/lunch/calendar.ts
Labels: 🛠 기능, 💅 디자인

#209 refactor: 초대장 생성 QA 수정사항 반영 (장소/날짜/시간 선택 파트)
  public/invitation/preview.png
  public/invitation/preview.webp
  src/components/common/BottomSheet.tsx
  src/components/common/TimeSelector.tsx
  src/components/invitation/create/InvitationDateTime.tsx
  src/components/invitation/create/InvitationInfo.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/components/invitation/create/InvitationPreview.tsx
  src/components/invitation/create/InvitationSelectTime.tsx
  src/pages/invitation/create.tsx
  src/types/invitation/create.ts
Labels: 🐞 버그, 💎 완료, 💅 디자인

#214 feat: 초대 목적 선택 시 초대장 예시(미리보기) 추가
  public/invitation/invitationPreview.png
  public/invitation/preview.png
  public/invitation/preview.webp
  src/assets/icons/Exit=medium.svg
  src/assets/icons/index.ts
  src/components/common/Icons.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/components/invitation/create/InvitationPreview.tsx
  src/constants/common/index.ts
Labels: 💎 완료, 🛠 기능

#215 fix: svg 검정색 처리 오류 및 포인트 페이지 스타일 변경
  public/point/Wrappedgift1.png
  src/components/lunch/calendar/LunchCalendarPointCard.tsx
Labels: 🐞 버그

#216 refactor: QA 수정사항 반영
  src/assets/icons/Call.svg
  src/assets/icons/Reviewer.svg
  src/assets/icons/index.ts
  src/components/common/Icons.tsx
  src/components/invitation/InvitationViewForm.tsx
  src/components/invitation/view/InvitationHostInfo.tsx
  src/components/invitation/view/InvitationHostInfoItem.tsx
  src/components/invitation/view/InvitationInfo.tsx
  src/components/invitation/view/InvitationQrInfo.tsx
  src/components/invitation/view/InvitationViewFooter.tsx
  src/constants/common/index.ts
  src/constants/invitation/viewTexts.ts
Labels: 🐞 버그, 💎 완료, 🛠 기능, 💅 디자인

#226 refactor: 달력 페이지, 리뷰 상세 모달, 리뷰 버튼 수정
  src/components/lunch/calendar/LunchCalendarCafeteria.tsx
  src/components/lunch/calendar/LunchCalendarDetailsSlide.tsx
  src/components/lunch/calendar/LunchCalendarEatOut.tsx
  src/components/lunch/calendar/LunchCalendarForm.tsx
  src/components/lunch/calendar/LunchCalendarListItem.tsx
  src/components/lunch/calendar/LunchCalendarLunchBox.tsx
  src/components/lunch/calendar/LunchCalendarMain.tsx
  src/components/lunch/calendar/LunchCalendarRatingBtn.tsx
  src/components/lunch/calendar/LunchCalendarReview.tsx
  src/components/lunch/calendar/LunchCalendarSearch.tsx
  src/components/lunch/calendar/LunchCalendarWriteBtn.tsx
Labels: 🐞 버그, 💎 완료, 💅 디자인

#227 fix: 초대장 전송 실패시 에러메세지 출력 오류 수정, 공통 Alert 프리텐다드 옵션 추가
  src/components/common/Alert.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/styles/theme.ts
  src/types/common/alert.ts
Labels: 🐞 버그, 💎 완료, 💅 디자인

#229 refactor: 오늘 점심 룰렛 리팩토링
  src/components/lunch/LunchRest.tsx
  src/components/lunch/LunchRoulette.tsx
  src/components/lunch/review/LunchReview.tsx
  src/components/lunch/review/LunchReviewPhotos.tsx
  src/components/lunch/review/LunchReviewsByRest.tsx
  src/components/lunch/roulette/LunchRoulettePopup.tsx
  src/constants/lunch/dummy.ts
  src/constants/lunch/index.ts
  src/pages/index.tsx
  src/pages/lunch/roulette.tsx
  src/stores/useRouletteStore.ts
  src/stores/useSaveStore.ts
  src/types/lunch/api.ts
Labels: 💎 완료

#230 fix: 초대장 발송 완료 페이지 수정
  src/components/invitation/InvitaitonEditForm.tsx
  src/components/invitation/create/InvitationDoneMessage.tsx
  src/components/invitation/edit/InvitationAddVisitorList.tsx
  src/components/invitation/edit/InvitationEdit.tsx
  src/components/invitation/view/InvitationInfo.tsx
  src/components/invitation/view/InvitationQrInfoCode.tsx
  src/components/user/UserInvitationList.tsx
  src/stores/useInvitationListStore.ts
  src/types/user/invitationList.ts
Labels: 🐞 버그, 💎 완료, 🛠 기능, 💅 디자인

#231 refactor: 초대장 생성 플로우 리팩토링
  src/components/common/Alert.tsx
  src/components/invitation/create/InvitationDateTime.tsx
  src/components/invitation/create/InvitationDoneBtn.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/components/invitation/create/InvitationPurposeContainer.tsx
  src/components/invitation/create/InvitationVisitorsContainer.tsx
  src/constants/common/index.ts
  src/constants/common/pages.ts
  src/constants/invitation/createTexts.ts
  src/constants/invitation/editTexts.ts
  src/pages/invitation/create.tsx
  src/types/common/pages.ts
  src/types/invitation/create.ts
Labels: 💎 완료

#234 refactor: 시연용 수정사항 반영 및 초대장 수정하기 오류 수정
  src/components/invitation/edit/InvitationEdit.tsx
  src/components/invitation/view/InvitaitionCarousel.tsx
  src/components/invitation/view/InvitationInfo.tsx
  src/components/invitation/view/InvitationQrInfoText.tsx
Labels: 💎 완료

#237 refactor: Q/A 기반 룰렛 리팩토링 및 버그 수정
  src/components/common/Alert.tsx
  src/components/home/service/HomeServiceCard.tsx
  src/components/home/service/index.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/components/invitation/create/InvitationVisitorsContainer.tsx
  src/components/lunch/LunchRoulette.tsx
  src/components/lunch/review/LunchReviewRestList.tsx
  src/components/lunch/roulette/LunchRoulettePopup.tsx
  src/components/lunch/roulette/LunchRouletteReviews.tsx
  src/hooks/useFetch.ts
  src/pages/lunch/roulette.tsx
  src/stores/useAlertStore.ts
  src/stores/useRouletteStore.ts
  src/types/common/alert.ts
  src/types/common/response.ts
  src/types/lunch/reviewList.ts
Labels: 🐞 버그, 💎 완료

#238 refactor: 초대 날짜/시간 선택 파트 예외처리 + 리팩토링
  src/components/common/RadioBtnBox.tsx
  src/components/invitation/InvitationCreateForm.tsx
  src/components/invitation/create/InvitationDateTime.tsx
  src/components/invitation/create/InvitationDoneMessage.tsx
  src/components/invitation/create/InvitationInfo.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/components/invitation/create/InvitationPlace.tsx
  src/components/invitation/create/InvitationPreview.tsx
  src/components/invitation/create/InvitationPurposeContainer.tsx
  src/components/invitation/create/InvitationSelectTime.tsx
  src/components/invitation/create/InvitationVisitorsContainer.tsx
  src/constants/common/index.ts
  src/constants/common/pages.ts
  src/stores/useTimeSelectorStore.ts
  src/types/invitation/create.ts
  src/utils/getCommonTimeList.ts
  src/utils/parseDate.ts
Labels: 🐞 버그, 💎 완료, 🛠 기능

#240 fix: 초대 목록, 초대장 담당 파트 오류 수정
  next.config.js
  src/components/invitation/view/InvitaitionCarousel.tsx
  src/components/invitation/view/InvitationHostInfoItem.tsx
  src/components/invitation/view/InvitationInfo.tsx
  src/components/invitation/view/InvitationQrInfoCode.tsx
  src/constants/common/index.ts
  src/constants/invitation/viewTexts.ts
Labels: 🐞 버그, 💎 완료, 💅 디자인

#251 feat: 오늘점심 룰렛 최초 진입 시 유저의 빌딩 근처 식당 추천 기능 추가
  src/components/lunch/LunchRest.tsx
  src/components/lunch/roulette/LunchRouletteReviews.tsx
  src/pages/api/lunch/lunchRequests.ts
  src/utils/processAddress.ts
Labels: 💎 완료, 🛠 기능

#254 refactor: 초대장 생성 플로우 + 담당 컴포넌트 체크
  src/components/common/Add.tsx
  src/components/common/AddressBook.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/Modal.tsx
  src/utils/checkValidation.ts
  src/utils/createTimeSlots.ts
  src/utils/getIsCommonData.ts
  src/utils/getPlaceId.ts
Labels: 💎 완료

#255 docs: 프로젝트 리드미 수정
  README.md
Labels: 📖 문서 수정, 💎 완료

#256 release: 2.1.0 ver
  README.md
  src/components/common/Add.tsx
  src/components/common/AddressBook.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/Modal.tsx
  src/components/lunch/LunchRest.tsx
  src/components/lunch/roulette/LunchRouletteReviews.tsx
  src/pages/api/lunch/lunchRequests.ts
  src/utils/checkValidation.ts
  src/utils/createTimeSlots.ts
  src/utils/getIsCommonData.ts
  src/utils/getPlaceId.ts
  src/utils/processAddress.ts
Labels: 🖥 배포

#258 docs: 프로젝트 리드미 수정
  README.md
Labels: 📖 문서 수정, 💎 완료

#259 docs: 프로젝트 리드미 업데이트
  README.md
Labels: 📖 문서 수정
