Repository livable-final/client, pull requests merged in 2023-09, with the labels that each got.

#2 feat: 글로벌 스타일링, theme 세팅 등 기초 프로젝트 세팅
  .babelrc
  .eslintrc.json
  next.config.js
  public/fonts/PretendardVariable.woff2
  public/icons/As.svg
  public/icons/Calendar.svg
  public/icons/Down.svg
  public/icons/Etc.svg
  public/icons/FixedtermWork.svg
  public/icons/Interview.svg
  public/icons/Location.svg
  public/icons/Right.svg
  public/icons/Up.svg
  public/icons/check=off.svg
  public/icons/check=on.svg
  public/icons/meeting.svg
  public/icons/seminar.svg
  src/components/common/Button.tsx
  src/components/common/Layout.tsx
  src/constants/common/constant.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/font.ts
  src/styles/globals.css
  src/styles/theme.ts
  src/types/common/button.ts
  tsconfig.json
Labels: 💎 완료

#10 design: font theme 설정
  src/styles/theme.ts
Labels: 💎 완료

#13 feat: 방문자 초대장 생성 컴포넌트 초안 구현 및 폴더/파일 구조 설정
  src/assets/icons/Info.svg
  src/assets/icons/index.ts
  src/components/common/Button.tsx
  src/components/common/Category.tsx
  src/components/common/Icons.tsx
  src/components/invitation/admin/index.tsx
  src/components/invitation/create/InvitationDate.tsx
  src/components/invitation/create/InvitationInfo.tsx
  src/components/invitation/create/InvitationPurpose.tsx
  src/components/invitation/mypage/index.tsx
  src/components/invitation/view/index.tsx
  src/constants/common/index.ts
  src/constants/invitation/adminTexts.ts
  src/constants/invitation/createTexts.ts
  src/constants/invitation/mypageTexts.ts
  src/constants/invitation/viewTexts.ts
  src/pages/invitation/admin.tsx
  src/pages/invitation/create.tsx
  src/pages/invitation/mypage.tsx
  src/pages/invitation/view.tsx
  src/stores/useNextComponentStore.ts
  src/types/invitation/admin.ts
  src/types/invitation/create.ts
  src/types/invitation/index.ts
  src/types/invitation/mypage.ts
  src/types/invitation/view.ts
  src/utils/mediaquery.ts
Labels: 📖 문서 수정, 💎 완료

#14 design: header 컴포넌트 구현
  src/components/common/Header.tsx
  src/constants/common/index.ts
  src/pages/index.tsx
  src/types/common/header.ts
Labels: 💎 완료

#15 design: input box 컴포넌트 구현
  src/assets/icons/Location.svg
  src/assets/icons/icon.svg
  src/assets/icons/index.ts
  src/components/common/ErrorMessage.tsx
  src/components/common/Input.tsx
  src/constants/common/index.ts
  src/pages/invitation/index.tsx
  src/types/common/errorMessage.ts
  src/types/common/input.ts
Labels: 💎 완료

#17 design: radio box 컴포넌트 구현
  .eslintrc.json
  src/assets/radioBtn/radioCheck.svg
  src/assets/radioBtn/radioUnCheck.svg
  src/components/common/RadioBtn.tsx
  src/pages/index.tsx
  src/types/common/RadioBtn.ts
Labels: 💎 완료

#24 feat: 토글 스위치 기능 추가
  src/components/common/Toggle.tsx
  src/constants/common/index.ts
  src/pages/index.tsx
Labels: 💎 완료

#28 feat: 길찾기 버튼 추가
  src/assets/icons/Direction.svg
  src/assets/icons/index.ts
  src/components/common/Icons.tsx
  src/components/invitation/view/InvitationFindRoadBtn.tsx
  src/constants/common/index.ts
  src/pages/index.tsx
  src/styles/theme.ts
Labels: 💎 완료

#30 design: 재사용 checkbox 컴포넌트 구현
  src/assets/icons/Check.svg
  src/assets/icons/UnCheck.svg
  src/assets/icons/index.ts
  src/components/common/CheckBox.tsx
  src/components/common/RadioBtn.tsx
  src/pages/index.tsx
  src/types/common/checkBox.ts
Labels: 💎 완료

#31 feat: 방문자 초대장 초대정보(장소/일시) 선택 컴포넌트 구현
  src/components/common/AddressBook.tsx
  src/components/common/CheckBox.tsx
  src/components/common/Input.tsx
  src/components/invitation/create/InvitationDate.tsx
  src/components/invitation/create/InvitationDateContainer.tsx
  src/components/invitation/create/InvitationInfo.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/components/invitation/create/InvitationNameList.tsx
  src/components/invitation/create/InvitationPurposeContainer.tsx
  src/constants/invitation/createTexts.ts
  src/pages/invitation/create.tsx
  src/styles/GlobalStyle.tsx
  src/types/invitation/create.ts
Labels: 💎 완료

#34 feat: view 페이지 url 변경 없이 여러 컴포넌트 랜더링
  src/components/Auth/ViewForm.tsx
  src/components/invitation/view/InvitationOfficeInfo.tsx
  src/components/invitation/view/index.tsx
  src/pages/invitation/view.tsx
  src/stores/useNextComponentStore.ts
  src/stores/useViewStore.ts
  src/types/invitation/view.ts
Labels: 💎 완료

#35 fix: ViewForm 경로 수정
  src/components/Auth/ViewForm.tsx
Labels: 📖 문서 수정

#39 design: 방문자 초대장 초대자 정보 페이지 레이아웃
  src/assets/icons/Copy_light.svg
  src/assets/icons/index.ts
  src/assets/icons/profille.svg
  src/components/Auth/ViewForm.tsx
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/components/invitation/view/InvitationHostInfo.tsx
  src/components/invitation/view/InvitationHostInfoItem.tsx
  src/constants/invitation/viewTexts.ts
  src/types/invitation/view.ts
Labels: 💎 완료

#44 fix: 페이지 이동을 위한 스토어를 공통으로 변경
  src/components/Auth/ViewForm.tsx
  src/components/invitation/view/InvitationHostInfo.tsx
  src/components/invitation/view/InvitationOfficeInfo.tsx
  src/pages/invitation/view.tsx
  src/stores/usePagesStore.ts
  src/types/common/pages.ts
  src/types/invitation/view.ts
Labels: 💎 완료

#48 feat: 룰렛 프로토타입 기능 추가
  package-lock.json
  package.json
  src/components/Roulette.tsx
  src/constants/lunch/rouletteTexts.ts
  src/pages/index.tsx
  src/styles/GlobalStyle.tsx
  src/types/lunch/menus.ts
  src/utils/getRandomNumber.ts
  src/utils/selectRandomItem.ts
Labels: 💎 완료

#50 feat: 전역 사용 가능한 모달 커스텀 훅 구현 (alert, confirm 버전 포함)
  src/components/common/Modal.tsx
  src/components/invitation/create/InvitationNameList.tsx
  src/components/invitation/create/InvitationPurposeContainer.tsx
  src/constants/common/index.ts
  src/constants/invitation/createTexts.ts
  src/pages/invitation/index.tsx
  src/stores/useModalStore.ts
  src/types/common/modal.ts
  src/types/invitation/create.ts
Labels: 💎 완료

#51 feat: 전역 사용 가능한 BottomSheet 구현
  src/components/common/BottomSheet.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/components/invitation/create/InvitationPurposeContainer.tsx
  src/pages/index.tsx
  src/stores/useBottomSheetStore.ts
  src/types/common/bottomSheet.ts
Labels: 💎 완료, 🔍 질문

#52 feat: 방문자 초대 완료(초대장 전송) 컴포넌트 구현
  src/assets/icons/Back.svg
  src/assets/icons/Send.svg
  src/assets/icons/index.ts
  src/components/common/Icons.tsx
  src/components/invitation/create/InvitationDoneBtn.tsx
  src/components/invitation/create/InvitationDoneContainer.tsx
  src/components/invitation/create/InvitationDoneMessage.tsx
  src/constants/common/index.ts
  src/constants/invitation/createTexts.ts
  src/pages/invitation/create.tsx
  src/types/invitation/create.ts
Labels: 💎 완료

#54 feat: FNB 기능 추가
  src/assets/icons/Home.svg
  src/assets/icons/index.ts
  src/components/common/Fnb.tsx
  src/components/common/Icons.tsx
  src/constants/common/index.ts
  src/constants/home/homeTexts.ts
  src/hooks/useIsScrollYTop.ts
  src/pages/index.tsx
  src/pages/invitation/mypage.tsx
  src/pages/lunch/index.tsx
  src/pages/user.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
Labels: 💎 완료

#56 feat: 달력 페이지 컴포넌트 레이아웃 구현
  .eslintrc.json
  package-lock.json
  package.json
  src/assets/icons/Bento.svg
  src/assets/icons/Camera.svg
  src/assets/icons/Chef.svg
  src/assets/icons/Confused.svg
  src/assets/icons/Gift.svg
  src/assets/icons/Plate.svg
  src/assets/icons/Plus=small.svg
  src/assets/icons/Rice.svg
  src/assets/icons/Search.svg
  src/assets/icons/Smile.svg
  src/assets/icons/ThumbsUp.svg
  src/assets/icons/XS_1.5.svg
  src/assets/icons/XS_black.svg
  src/assets/icons/check=off.svg
  src/assets/icons/check=on.svg
  src/assets/icons/index.ts
  src/components/common/Header.tsx
  src/components/common/Input.tsx
  src/components/lunch/LunchListItem.tsx
  src/components/lunch/LunchPhoto.tsx
  src/components/lunch/LunchRatingButton.tsx
  src/components/lunch/LunchReviewCategory.tsx
  src/components/lunch/LunchSelectButton.tsx
  src/components/lunch/LunchSubTitle.tsx
  src/components/lunch/LunchWriteButton.tsx
  src/components/lunch/calendar/LuchCalendarCafeteria.tsx
  src/components/lunch/calendar/LunchCalendarEatOut.tsx
  src/components/lunch/calendar/LunchCalendarForm.tsx
  src/components/lunch/calendar/LunchCalendarLunchBox.tsx
  src/components/lunch/calendar/LunchCalendarMain.tsx
  src/components/lunch/calendar/LunchCalendarMenu.tsx
  src/components/lunch/calendar/LunchCalendarReview.tsx
  src/components/lunch/calendar/LunchCalendarSearch.tsx
  src/constants/common/index.ts
  src/constants/lunch/index.ts
  src/pages/index.tsx
  src/pages/lunch/calendar.tsx
  src/pages/lunch/index.tsx
  src/pages/lunch/roulette.tsx
  src/styles/GlobalStyle.tsx
  src/styles/theme.ts
  src/types/lunch/calendar.ts
Labels: 💎 완료

#58 fix: 버튼 내 버튼 중복으로 생긴 Hydration Error 해결
  src/components/common/NameTag.tsx
Labels: 🐞 버그, 💎 완료

#57 feat/invitation-view 오피스정보, 빌딩정보 페이지 UI
  src/assets/icons/Bus.svg
  src/assets/icons/Copy.svg
  src/assets/icons/Subway.svg
  src/assets/icons/index.ts
  src/assets/testImg/TestBuildingImg.svg
  src/assets/testImg/TestMap.svg
  src/assets/testImg/index.ts
  src/components/auth/ViewForm.tsx
  src/components/common/Icons.tsx
  src/components/invitation/view/InvitationBuildingInfo.tsx
  src/components/invitation/view/InvitationBuildingInfoItem.tsx
  src/components/invitation/view/InvitationBuildingMap.tsx
  src/components/invitation/view/InvitationBuildingPublicTransportItem.tsx
  src/components/invitation/view/InvitationBuildingTitle.tsx
  src/components/invitation/view/InvitationFindRoadBtn.tsx
  src/components/invitation/view/InvitationOfficeInfo.tsx
  src/components/invitation/view/InvitationOfficeLocation.tsx
  src/components/invitation/view/InvitationOfficeMap.tsx
  src/components/invitation/view/InvitationOfficeVisitTip.tsx
  src/constants/common/index.ts
  src/constants/invitation/viewTexts.ts
  src/types/invitation/view.ts
Labels: 💎 완료

#66 refactor: input box 리팩토링
  src/components/common/Input.tsx
  src/pages/invitation/index.tsx
  src/types/common/input.ts
Labels: 💎 완료

#64 design: GodoM 서브폰트 추가
  src/assets/fonts/GodoM.ttf
  src/components/common/Layout.tsx
  src/styles/font.ts
  src/styles/theme.ts
Labels: 💎 완료, 🚨 긴급

#67 design: 마이페이지 UI 작업
  src/assets/icons/Coin.svg
  src/assets/icons/Setting.svg
  src/assets/icons/index.ts
  src/components/common/Bnb.tsx
  src/components/common/Icons.tsx
  src/components/user/UserInfo.tsx
  src/components/user/UserNavigator.tsx
  src/components/user/UserPoint.tsx
  src/components/user/UserTitle.tsx
  src/constants/common/index.ts
  src/constants/user/userTexts.ts
  src/pages/index.tsx
  src/pages/lunch/index.tsx
  src/pages/user.tsx
  src/styles/GlobalStyle.tsx
  src/types/common/icon.ts
  src/types/user/index.ts
Labels: 💎 완료

#62 fix: 공백, css 코드 수정, radioBtn.ts 파일명 수정
  src/components/invitation/view/InvitationBuildingInfo.tsx
  src/components/invitation/view/InvitationBuildingInfoItem.tsx
  src/components/invitation/view/InvitationBuildingMap.tsx
  src/components/invitation/view/InvitationBuildingPublicTransportItem.tsx
  src/components/invitation/view/InvitationBuildingTitle.tsx
  src/types/common/radioBtn.ts
Labels: 🐞 버그

#69 feat: 방문자 초대장 생성 플로우 구현 (usePagesStore 사용)
  src/assets/icons/Plus=small.svg
  src/components/common/Add.tsx
  src/components/common/Category.tsx
  src/components/common/Header.tsx
  src/components/common/Icons.tsx
  src/components/common/Modal.tsx
  src/components/invitation/InvitationCreateForm.tsx
  src/components/invitation/create/InvitationDate.tsx
  src/components/invitation/create/InvitationDateContainer.tsx
  src/components/invitation/create/InvitationDoneBtn.tsx
  src/components/invitation/create/InvitationDoneContainer.tsx
  src/components/invitation/create/InvitationDoneMessage.tsx
  src/components/invitation/create/InvitationInfo.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/components/invitation/create/InvitationPurposeContainer.tsx
  src/components/invitation/create/InvitationVisitorsContainer.tsx
  src/components/invitation/create/InvitationVisitorsList.tsx
  src/constants/common/index.ts
  src/constants/invitation/createTexts.ts
  src/pages/invitation/create.tsx
  src/stores/useInvitationHeaderTitleStore.ts
  src/types/common/input.ts
  src/types/invitation/create.ts
Labels: 💎 완료, 🛠 기능

#70 feat: 캘린더 컴포넌트 구현
  public/ruppy.png
  src/assets/icons/DateDish.svg
  src/assets/icons/DateDishNoPhoto.svg
  src/assets/icons/LeftSmall.svg
  src/assets/icons/index.ts
  src/components/lunch/LunchWriteButton.tsx
  src/components/lunch/calendar/LunchCalendarForm.tsx
  src/pages/lunch/point.tsx
  src/types/lunch/calendar.ts
Labels: 💎 완료

#72 design: 초대 장소 컴포넌트 레이아웃 구현 (+ 작은 수정들)
  package-lock.json
  package.json
  src/components/common/AddressBook.tsx
  src/components/common/BottomSheet.tsx
  src/components/common/Button.tsx
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/components/common/RadioBtn.tsx
  src/components/invitation/create/InvitationDateTime.tsx
  src/components/invitation/create/InvitationDoneBtn.tsx
  src/components/invitation/create/InvitationInfo.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/components/invitation/create/InvitationPlace.tsx
  src/components/invitation/create/InvitationPurposeContainer.tsx
  src/components/invitation/create/InvitationVisitorsContainer.tsx
  src/components/invitation/create/InvitationVisitorsList.tsx
  src/constants/invitation/createTexts.ts
  src/pages/index.tsx
  src/pages/invitation/create.tsx
  src/pages/invitation/index.tsx
  src/types/common/header.ts
Labels: 💎 완료, 💅 디자인

#74 design: 방문자 초대장 메인 페이지
  src/assets/cafe.png
  src/assets/icons/Calender-Fill.svg
  src/assets/icons/InfoCategory.svg
  src/assets/icons/Location-fill.svg
  src/assets/icons/index.ts
  src/components/auth/ViewForm.tsx
  src/components/invitation/InvitationViewForm.tsx
  src/components/invitation/view/InvitaitionCarousel.tsx
  src/components/invitation/view/InvitationCarouselContainer.tsx
  src/components/invitation/view/InvitationHostInfo.tsx
  src/components/invitation/view/InvitationInfo.tsx
  src/components/invitation/view/InvitationInfoCategory.tsx
  src/components/invitation/view/InvitationInfoContainer.tsx
  src/components/invitation/view/InvitationViewFooter.tsx
  src/constants/invitation/viewTexts.ts
  src/pages/invitation/view.tsx
  src/types/invitation/view.ts
Labels: 💎 완료, 💅 디자인

#75 design: 메인 홈 레이아웃 작업
  src/assets/icons/Barcode.svg
  src/assets/icons/Bell.svg
  src/assets/icons/Down.svg
  src/assets/icons/Line.svg
  src/assets/icons/Rights.svg
  src/assets/icons/Roulette.svg
  src/assets/icons/Sunny.svg
  src/assets/icons/TearOffCalendar.svg
  src/assets/icons/index.ts
  src/components/common/Bnb.tsx
  src/components/common/Icons.tsx
  src/components/common/Layout.tsx
  src/components/common/Title.tsx
  src/components/home/HomeCard.tsx
  src/components/home/HomeContents.tsx
  src/components/home/HomeServey.tsx
  src/components/home/banner/index.tsx
  src/components/home/bulletin/HomeBulletinDate.tsx
  src/components/home/bulletin/HomeBulletinNotice.tsx
  src/components/home/bulletin/HomeBulletinWeather.tsx
  src/components/home/bulletin/index.tsx
  src/components/home/cafeteria/HomeCafeteriaToggle.tsx
  src/components/home/cafeteria/index.tsx
  src/components/home/reception/HomeReceptionProgress.tsx
  src/components/home/reception/index.tsx
  src/components/home/service/HomeServiceCard.tsx
  src/components/home/service/index.tsx
  src/constants/common/index.ts
  src/constants/home/homeTexts.ts
  src/pages/index.tsx
  src/pages/temp.tsx
  src/styles/font.ts
  src/styles/theme.ts
  src/types/common/title.ts
  src/types/home/index.ts
  src/utils/getTodayDate.ts
Labels: 💎 완료, 💅 디자인

#77 feat: 캘린더 상세 슬라이드 모달 및 리뷰작성 일부 플로우 구현
  next.config.js
  package-lock.json
  package.json
  src/assets/icons/Delicious.svg
  src/assets/icons/Location20.svg
  src/assets/icons/index.ts
  src/components/lunch/LunchListItem.tsx
  src/components/lunch/LunchRatingButton.tsx
  src/components/lunch/LunchSelectButton.tsx
  src/components/lunch/LunchWriteButton.tsx
  src/components/lunch/calendar/LunchCalendarCafeteria.tsx
  src/components/lunch/calendar/LunchCalendarDetailsSlide.tsx
  src/components/lunch/calendar/LunchCalendarEatOut.tsx
  src/components/lunch/calendar/LunchCalendarForm.tsx
  src/components/lunch/calendar/LunchCalendarLunchBox.tsx
  src/components/lunch/calendar/LunchCalendarMain.tsx
  src/components/lunch/calendar/LunchCalendarMenu.tsx
  src/components/lunch/calendar/LunchCalendarReview.tsx
  src/components/lunch/calendar/LunchCalendarSearch.tsx
  src/stores/usePagesStore.ts
  src/types/common/pages.ts
  src/types/lunch/calendar.ts
Labels: 🔧 진행중

#78 fix: build 오류 수정
  .eslintrc.json
  src/components/common/RadioBtn.tsx
  src/components/invitation/InvitationCreateForm.tsx
  src/components/invitation/InvitationViewForm.tsx
  src/components/invitation/create/InvitationDateTime.tsx
  src/components/invitation/create/InvitationVisitorsList.tsx
  src/components/lunch/calendar/LunchCalendarCafeteria.tsx
  src/pages/invitation/create.tsx
  src/pages/temp.tsx
Labels: 💎 완료

#83 feat: openWeatherAPI 연결 및 axios 추가
  next.config.js
  package-lock.json
  package.json
  src/assets/icons/index.ts
  src/assets/icons/weather/BrokenClouds.svg
  src/assets/icons/weather/ClearDay.svg
  src/assets/icons/weather/ClearNight.svg
  src/assets/icons/weather/Clouds.svg
  src/assets/icons/weather/FewClouds.svg
  src/assets/icons/weather/Mist.svg
  src/assets/icons/weather/Rain.svg
  src/assets/icons/weather/ShowerRain.svg
  src/assets/icons/weather/Snow.svg
  src/assets/icons/weather/ThunderStorm.svg
  src/components/common/Icons.tsx
  src/components/home/HomeContents.tsx
  src/components/home/bulletin/HomeBulletinWeather.tsx
  src/constants/common/index.ts
  src/constants/home/homeTexts.ts
  src/pages/_app.tsx
  src/pages/api/axios.ts
  src/pages/api/home/getWeather.ts
  src/utils/getCelsius.ts
  src/utils/getWeatherIcon.ts
Labels: 💎 완료

#86 design: 방문자 출입증 상세페이지 레이아웃 , 상세페이지 연결
  src/components/invitation/InvitationViewForm.tsx
  src/components/invitation/view/InvitationHostInfo.tsx
  src/components/invitation/view/InvitationInfo.tsx
  src/components/invitation/view/InvitationInfoContainer.tsx
  src/components/invitation/view/InvitationQrInfo.tsx
  src/components/invitation/view/InvitationQrInfoCode.tsx
  src/components/invitation/view/InvitationQrInfoText.tsx
  src/constants/invitation/viewTexts.ts
  src/types/invitation/view.ts
Labels: 💎 완료, 💅 디자인

#89 design: 오점완 홈(메인) 파트 UI 작업
  src/assets/fonts/GangwonPower.otf
  src/assets/fonts/Yeongdeok.ttf
  src/assets/icons/Barcode.svg
  src/assets/icons/Confused.svg
  src/assets/icons/Home.svg
  src/assets/icons/Lunch.svg
  src/assets/icons/LunchCalendar.svg
  src/assets/icons/Rank1.svg
  src/assets/icons/Rank2.svg
  src/assets/icons/Rank3.svg
  src/assets/icons/Reviewer.svg
  src/assets/icons/Rights.svg
  src/assets/icons/Smile.svg
  src/assets/icons/ThumbsUp.svg
  src/assets/icons/index.ts
  src/assets/icons/profile.svg
  src/assets/menu.png
  src/components/common/Banner.tsx
  src/components/common/Bnb.tsx
  src/components/common/Card.tsx
  src/components/common/Icons.tsx
  src/components/common/Layout.tsx
  src/components/common/Title.tsx
  src/components/home/HomeContents.tsx
  src/components/home/HomeServey.tsx
  src/components/home/bulletin/index.tsx
  src/components/home/cafeteria/index.tsx
  src/components/home/reception/index.tsx
  src/components/home/service/index.tsx
  src/components/lunch/main/LunchMainContents.tsx
  src/components/lunch/main/LunchMainRanking.tsx
  src/components/lunch/main/LunchMainRankingCard.tsx
  src/components/lunch/main/LunchMainRankingMenus.tsx
  src/components/lunch/main/LunchMainRankingTitle.tsx
  src/components/lunch/main/LunchMainReviews.tsx
  src/components/lunch/review/LunchReview.tsx
  src/components/lunch/review/LunchReviewPhotos.tsx
  src/components/lunch/review/LunchReviewRatings.tsx
  src/constants/common/index.ts
  src/constants/lunch/dummy.ts
  src/constants/lunch/index.ts
  src/constants/lunch/rouletteTexts.ts
  src/pages/api/lunch/getRanking.ts
  src/pages/lunch/index.tsx
  src/styles/font.ts
  src/styles/theme.ts
  src/types/common/card.ts
  src/types/home/index.ts
  src/types/lunch/ranking.ts
  src/types/lunch/ratings.ts
  src/types/lunch/reviewList.ts
  src/utils/getCelsius.ts
  src/utils/getTimeDiff.ts
Labels: 💎 완료, 💅 디자인

#90 feat: 달력 모달 닫기 기능 수정
  src/components/lunch/LunchRatingButton.tsx
  src/components/lunch/calendar/LunchCalendarDetailsSlide.tsx
  src/components/lunch/calendar/LunchCalendarForm.tsx
Labels: 🛠 기능

#88 design: 내 초대 목록 레이아웃 구현
  src/components/user/UserInvitationList.tsx
  src/components/user/UserInvitationListItem.tsx
  src/constants/user/userTexts.ts
  src/pages/user/index.tsx
  src/pages/user/invitation-list.tsx
  src/types/user/invitationList.ts
Labels: 💎 완료, 💅 디자인

#92 feat: Card Component 전역화 작업
  src/components/common/Banner.tsx
  src/components/common/Card.tsx
  src/components/home/HomeServey.tsx
  src/components/home/bulletin/index.tsx
  src/components/home/cafeteria/index.tsx
  src/components/home/reception/index.tsx
  src/components/home/service/index.tsx
  src/types/common/card.ts
Labels: 💎 완료

#96 design: 오점완 리뷰 상세 UI 작업
  public/menu.png
  src/components/common/Banner.tsx
  src/components/home/HomeServey.tsx
  src/components/home/bulletin/HomeBulletinNotice.tsx
  src/components/home/bulletin/index.tsx
  src/components/home/cafeteria/index.tsx
  src/components/home/reception/HomeReceptionProgress.tsx
  src/components/home/reception/index.tsx
  src/components/home/service/index.tsx
  src/components/lunch/LunchCard.tsx
  src/components/lunch/LunchSubTitle.tsx
  src/components/lunch/detail/LunchDetailContents.tsx
  src/components/lunch/detail/index.tsx
  src/components/lunch/main/LunchMainContents.tsx
  src/components/lunch/main/LunchMainRanking.tsx
  src/components/lunch/main/LunchMainRankingMenus.tsx
  src/components/lunch/main/LunchMainRankingTitle.tsx
  src/components/lunch/main/LunchMainReviews.tsx
  src/components/lunch/review/LunchReview.tsx
  src/components/lunch/review/LunchReviews.tsx
  src/constants/lunch/index.ts
  src/pages/lunch/index.tsx
  src/stores/useReviewStore.ts
  src/types/lunch/calendar.ts
  src/types/lunch/card.ts
  src/types/lunch/reviewList.ts
Labels: 💎 완료, 💅 디자인

#101 feat: axios API URL 세팅 및 설정 추가
  src/components/home/bulletin/HomeBulletinWeather.tsx
  src/pages/api/axios.ts
  src/pages/api/home/homeRequests.ts
  src/pages/api/invitation/createRequests.ts
  src/pages/api/lunch/lunchRequests.ts
Labels: 💎 완료

#99 design: 방문자 초대 날짜/시간 생성 컴포넌트 초안 레이아웃 및 전체 코드 리팩토링
  package-lock.json
  package.json
  src/assets/icons/Send.svg
  src/components/common/BottomSheet.tsx
  src/components/common/Category.tsx
  src/components/common/TimeSelector.tsx
  src/components/common/Toggle.tsx
  src/components/invitation/create/InvitationDateTime.tsx
  src/components/invitation/create/InvitationDoneBtn.tsx
  src/components/invitation/create/InvitationDoneContainer.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/components/invitation/create/InvitationPurposeContainer.tsx
  src/components/invitation/create/InvitationSelectTime.tsx
  src/components/invitation/create/InvitationVisitorsContainer.tsx
  src/components/invitation/create/InvitationVisitorsList.tsx
  src/constants/common/index.ts
  src/constants/invitation/createTexts.ts
  src/pages/invitation/create.tsx
  src/types/invitation/create.ts
  src/utils/createTimeSlot.ts
  src/utils/createTimeSlots.ts
  src/utils/parseDate.ts
Labels: 🚨 긴급, 💅 디자인

#104 design: 초대 목록 바텀 시트, 삭제 모달 구현
  src/components/user/UserInvitationList.tsx
  src/components/user/UserInvitationListEdit.tsx
  src/components/user/UserInvitationListItem.tsx
  src/constants/user/userInvitationTexts.ts
Labels: 💎 완료, 💅 디자인

#105 feat: 사진등록 팝업창 (바텀시트) 구현
  src/assets/icons/CameraFlash.svg
  src/assets/icons/Check.svg
  src/assets/icons/check=off.svg
  src/assets/icons/index.ts
  src/components/common/Icons.tsx
  src/components/lunch/calendar/LunchCalendarBottomSheet.tsx
  src/components/lunch/calendar/LunchCalendarCafeteria.tsx
  src/components/lunch/calendar/LunchCalendarEatOut.tsx
  src/components/lunch/calendar/LunchCalendarListItem.tsx
  src/components/lunch/calendar/LunchCalendarLunchBox.tsx
  src/components/lunch/calendar/LunchCalendarMain.tsx
  src/components/lunch/calendar/LunchCalendarMenu.tsx
  src/components/lunch/calendar/LunchCalendarPhoto.tsx
  src/components/lunch/calendar/LunchCalendarRatingBtn.tsx
  src/components/lunch/calendar/LunchCalendarReview.tsx
  src/components/lunch/calendar/LunchCalendarReviewCategory.tsx
  src/components/lunch/calendar/LunchCalendarSearch.tsx
  src/components/lunch/calendar/LunchCalendarSelectBtn.tsx
  src/components/lunch/calendar/LunchCalendarWriteBtn.tsx
  src/constants/common/index.ts
  src/constants/lunch/index.ts
  src/stores/useSaveStore.ts
  src/types/lunch/calendar.ts
Labels: 💎 완료

#109 design: 랭킹별 리뷰 UI 작업
  src/assets/icons/Close.svg
  src/assets/icons/Down.svg
  src/assets/icons/Top.svg
  src/assets/icons/index.ts
  src/components/common/Header.tsx
  src/components/common/Icons.tsx
  src/components/common/ToTop.tsx
  src/components/lunch/LunchCard.tsx
  src/components/lunch/LunchMainContents.tsx
  src/components/lunch/detail/LunchDetailContents.tsx
  src/components/lunch/detail/index.tsx
  src/components/lunch/main/LunchMainRanking.tsx
  src/components/lunch/main/LunchMainRankingMenus.tsx
  src/components/lunch/main/LunchMainRankingTitle.tsx
  src/components/lunch/ranking/LunchRankingPodium.tsx
  src/components/lunch/ranking/LunchRankingReviews.tsx
  src/components/lunch/ranking/LunchRankings.tsx
  src/components/lunch/ranking/index.tsx
  src/components/lunch/review/LunchReview.tsx
  src/components/lunch/review/LunchReviewPhotos.tsx
  src/components/lunch/review/LunchReviews.tsx
  src/components/lunch/review/LunchReviewsByRanking.tsx
  src/constants/common/index.ts
  src/constants/lunch/dummy.ts
  src/constants/lunch/index.ts
  src/pages/api/lunch/lunchRequests.ts
  src/pages/lunch/index.tsx
  src/types/common/header.ts
  src/types/lunch/card.ts
  src/types/lunch/lunchRequests.ts
  src/types/lunch/menuTopTen.ts
  src/types/lunch/ranking.ts
  src/types/lunch/reviewList.ts
  src/types/lunch/reviewPhotos.ts
  src/utils/getWeatherIcon.ts
Labels: 💎 완료, 💅 디자인

#111 feat: Home 리디자인 및 세부 기능 추가
  src/assets/icons/Bell.svg
  src/assets/icons/ProfileWithBg.svg
  src/assets/icons/Servey.svg
  src/assets/icons/ServiceCafeteria.svg
  src/assets/icons/ServiceCalendar.svg
  src/assets/icons/ServiceInvitation.svg
  src/assets/icons/ServiceParking.svg
  src/assets/icons/ServiceReception.svg
  src/assets/icons/ServiceTemp.svg
  src/assets/icons/ThumbsUp.svg
  src/assets/icons/index.ts
  src/components/common/Banner.tsx
  src/components/common/Bnb.tsx
  src/components/common/Icons.tsx
  src/components/common/Title.tsx
  src/components/home/HomeServey.tsx
  src/components/home/cafeteria/HomeCafeteriaToggle.tsx
  src/components/home/cafeteria/index.tsx
  src/components/home/service/HomeServiceCard.tsx
  src/components/lunch/detail/index.tsx
  src/components/lunch/review/LunchReview.tsx
  src/components/lunch/review/LunchReviewRatings.tsx
  src/components/user/UserInfo.tsx
  src/components/user/UserPoint.tsx
  src/constants/common/index.ts
  src/constants/home/homeTexts.ts
  src/constants/lunch/index.ts
  src/pages/index.tsx
  src/pages/lunch/index.tsx
  src/pages/user/index.tsx
  src/stores/useReviewStore.ts
  src/styles/GlobalStyle.tsx
  src/types/common/header.ts
  src/types/home/index.ts
  src/utils/getWeatherIcon.ts
Labels: 💎 완료

#117 feat: 404 에러 페이지 추가
  src/assets/icons/Error.svg
  src/assets/icons/index.ts
  src/components/common/Bnb.tsx
  src/components/common/Header.tsx
  src/components/lunch/detail/LunchDetailContents.tsx
  src/components/lunch/ranking/LunchRankingPodium.tsx
  src/components/lunch/review/LunchReview.tsx
  src/components/lunch/review/LunchReviewPhotos.tsx
  src/components/lunch/review/LunchReviews.tsx
  src/constants/common/index.ts
  src/pages/404.tsx
  src/pages/index.tsx
  src/pages/lunch/index.tsx
  src/styles/theme.ts
  src/types/lunch/reviewList.ts
Labels: 🐞 버그, 💎 완료

#118 refactor: 모달 공용 컴포넌트 리팩토링, 버튼 위치 변경, props 추가
  src/components/common/Modal.tsx
  src/components/invitation/create/InvitationDoneBtn.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/constants/common/index.ts
  src/constants/invitation/createTexts.ts
  src/types/common/modal.ts
  src/types/invitation/create.ts
Labels: 💎 완료, 🛠 기능

#122 feat: 임시 로그인 구현
  next.config.js
  src/components/auth/AuthForm.tsx
  src/components/common/Category.tsx
  src/components/common/Title.tsx
  src/components/home/index.tsx
  src/constants/common/index.ts
  src/constants/common/pages.ts
  src/pages/index.tsx
  src/pages/lunch/index.tsx
  src/stores/useSaveStore.ts
Labels: 💎 완료

#127 refactor: 방문자 초대장 생성 파트 리팩토링 + 유효성 검사
  src/components/common/BottomSheet.tsx
  src/components/common/ErrorMessage.tsx
  src/components/common/Input.tsx
  src/components/common/RadioBtn.tsx
  src/components/common/TimeSelector.tsx
  src/components/home/index.tsx
  src/components/invitation/create/InvitationDateTime.tsx
  src/components/invitation/create/InvitationDoneBtn.tsx
  src/components/invitation/create/InvitationInfo.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/components/invitation/create/InvitationPlace.tsx
  src/components/invitation/create/InvitationPurposeContainer.tsx
  src/components/invitation/create/InvitationSelectTime.tsx
  src/components/invitation/create/InvitationVisitorsContainer.tsx
  src/constants/common/index.ts
  src/stores/useInvitationCreateStore.ts
  src/stores/usePagesStore.ts
  src/types/common/errorMessage.ts
  src/types/common/input.ts
  src/types/common/pages.ts
  src/types/invitation/create.ts
  src/utils/checkValidation.ts
Labels: 💎 완료

#128 feat: Main Home 1차 API 연동
  src/assets/icons/My.svg
  src/assets/icons/Servey.svg
  src/assets/icons/index.ts
  src/components/common/Bnb.tsx
  src/components/common/Header.tsx
  src/components/common/Icons.tsx
  src/components/common/RadioBtn.tsx
  src/components/home/HomeContents.tsx
  src/components/home/HomeServey.tsx
  src/components/home/bulletin/HomeBulletinWeather.tsx
  src/components/home/index.tsx
  src/components/lunch/LunchMainContents.tsx
  src/components/lunch/LunchRoulette.tsx
  src/components/lunch/calendar/LunchCalendarCafeteria.tsx
  src/components/lunch/calendar/LunchCalendarEatOut.tsx
  src/components/lunch/calendar/LunchCalendarLunchBox.tsx
  src/components/lunch/calendar/LunchCalendarSearch.tsx
  src/components/lunch/review/LunchReviewsByRanking.tsx
  src/components/user/UserInfo.tsx
  src/components/user/UserInvitationListEdit.tsx
  src/constants/common/index.ts
  src/constants/common/pages.ts
  src/constants/home/homeTexts.ts
  src/constants/lunch/index.ts
  src/constants/lunch/rouletteTexts.ts
  src/hooks/useFetch.ts
  src/pages/api/axios.ts
  src/pages/api/home/homeRequests.ts
  src/pages/api/lunch/lunchRequests.ts
  src/pages/index.tsx
  src/pages/invitation/index.tsx
  src/pages/lunch/roulette.tsx
  src/pages/temp.tsx
  src/stores/useIdStore.ts
  src/stores/useInvitationCreateStore.ts
  src/stores/useSaveStore.ts
  src/types/common/id.ts
  src/types/common/response.ts
  src/types/common/title.ts
  src/types/home/api.ts
  src/types/home/index.ts
  src/types/lunch/lunchRequests.ts
  src/types/lunch/menus.ts
  src/types/lunch/response.ts
  src/types/user/index.ts
  src/utils/selectRandomItem.ts
Labels: 💎 완료

#129 design: 초대장 수정 페이지 , 초대자 추가 바텀시트 레이아웃 및 페이지 연결
  src/components/common/NameTag.tsx
  src/components/invitation/create/InvitationVisitorsList.tsx
  src/components/invitation/edit/InvitationAddVisitorList.tsx
  src/components/invitation/edit/InvitationEdit.tsx
  src/components/user/UserInvitationListEdit.tsx
  src/constants/invitation/editTexts.ts
  src/constants/invitation/mypageTexts.ts
  src/pages/invitation/edit.tsx
  src/types/common/nameTag.ts
  src/types/invitation/edit.ts
  src/types/invitation/mypage.ts
Labels: 💎 완료, 💅 디자인

#130 design: Roulette UI 작업 및 API 연동
  package-lock.json
  package.json
  src/assets/icons/Bell.svg
  src/components/auth/AuthForm.tsx
  src/components/common/Header.tsx
  src/components/home/index.tsx
  src/components/lunch/LunchRest.tsx
  src/components/lunch/LunchRoulette.tsx
  src/components/lunch/LunchSubTitle.tsx
  src/components/lunch/review/LunchReviewsByRest.tsx
  src/constants/common/pages.ts
  src/constants/lunch/dummy.ts
  src/constants/lunch/index.ts
  src/hooks/useFetch.ts
  src/pages/_document.tsx
  src/pages/api/lunch/lunchRequests.ts
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/lunch/index.tsx
  src/pages/lunch/roulette.tsx
  src/types/common/header.ts
  src/types/lunch/api.ts
  src/types/lunch/calendar.ts
  src/types/lunch/response.ts
  src/utils/selectRandomItem.ts
Labels: 💎 완료, 💅 디자인

#135 refactor: 미사용 코드 삭제, 콘솔로그 삭제, 타입 추가
  src/components/common/RadioBtn.tsx
  src/components/invitation/create/InvitationDateTime.tsx
  src/components/invitation/create/InvitationDoneBtn.tsx
  src/components/invitation/create/InvitationInfo.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/components/invitation/create/InvitationPlace.tsx
  src/components/invitation/create/InvitationVisitorsContainer.tsx
  src/components/invitation/create/InvitationVisitorsList.tsx
  src/components/invitation/edit/InvitationAddVisitorList.tsx
  src/pages/api/invitation/createRequests.ts
  src/types/common/radioBtn.ts
  src/types/invitation/admin.ts
  src/types/invitation/api.ts
  src/types/invitation/create.ts
  src/types/invitation/index.ts
  src/utils/getIsCommonData.ts
  src/utils/getPlaceId.ts
Labels: 💎 완료

#137 feat: 외식 파트 글쓰기 api 연결
  package-lock.json
  src/assets/icons/Plus=small.svg
  src/components/lunch/LunchRest.tsx
  src/components/lunch/calendar/LunchCalendarBottomSheet.tsx
  src/components/lunch/calendar/LunchCalendarCafeteria.tsx
  src/components/lunch/calendar/LunchCalendarEatOut.tsx
  src/components/lunch/calendar/LunchCalendarListItem.tsx
  src/components/lunch/calendar/LunchCalendarLunchBox.tsx
  src/components/lunch/calendar/LunchCalendarMain.tsx
  src/components/lunch/calendar/LunchCalendarMenu.tsx
  src/components/lunch/calendar/LunchCalendarPhoto.tsx
  src/components/lunch/calendar/LunchCalendarPointInform.tsx
  src/components/lunch/calendar/LunchCalendarRatingBtn.tsx
  src/components/lunch/calendar/LunchCalendarReview.tsx
  src/components/lunch/calendar/LunchCalendarReviewCategory.tsx
  src/components/lunch/calendar/LunchCalendarSearch.tsx
  src/components/lunch/calendar/LunchCalendarSelectBtn.tsx
  src/constants/common/pages.ts
  src/constants/lunch/index.ts
  src/pages/api/lunch/calendarRequests.ts
  src/pages/lunch/write.tsx
  src/stores/useSaveStore.ts
  src/stores/useWriteStore.ts
  src/types/lunch/calendar.ts
  src/utils/key.ts
Labels: 💎 완료

#140 feat: 메세지 저장 기능, 면접일 때 방문자 추가 제한
  src/components/common/CheckBox.tsx
  src/components/common/NameTag.tsx
  src/components/common/RadioBtnBox.tsx
  src/components/invitation/create/InvitationDoneMessage.tsx
  src/components/invitation/create/InvitationInfoContainer.tsx
  src/components/invitation/create/InvitationVisitorsContainer.tsx
  src/components/invitation/create/InvitationVisitorsList.tsx
  src/components/invitation/edit/InvitationAddVisitorList.tsx
  src/stores/useSaveStore.ts
  src/types/common/nameTag.ts
  src/types/common/radioBtn.ts
  src/types/invitation/api.ts
  src/types/invitation/create.ts
Labels: 💎 완료, 🛠 기능

#142 feat: 방문자 초대장 메인 페이지 api 연결
  src/assets/icons/Plus=small.svg
  src/components/invitation/InvitationViewForm.tsx
  src/components/invitation/view/InvitaitionCarousel.tsx
  src/components/invitation/view/InvitationCarouselContainer.tsx
  src/components/invitation/view/InvitationHostInfo.tsx
  src/components/invitation/view/InvitationInfo.tsx
  src/components/invitation/view/InvitationInfoContainer.tsx
  src/pages/api/invitation/viewRequests.ts
  src/types/invitation/api.ts
  src/types/invitation/view.ts
Labels: 💎 완료

#144 feat: 홈, 오늘 점심 API 연동 테스트
  package-lock.json
  package.json
  public/roulette/again.webp
  public/roulette/againPressed.webp
  public/roulette/lock.webp
  public/roulette/lockPressed.webp
  public/roulette/push.webp
  public/roulette/pushPressed.webp
  public/roulette/roulette.png
  public/roulette/rouletteActive.webp
  public/roulette/unLock.webp
  public/roulette/unLockPressed.webp
  src/assets/fonts/DNFBitBit.ttf
  src/assets/images/index.ts
  src/components/common/Header.tsx
  src/components/common/Layout.tsx
  src/components/home/bulletin/HomeBulletinWeather.tsx
  src/components/invitation/InvitationViewForm.tsx
  src/components/lunch/LunchRoulette.tsx
  src/components/lunch/detail/LunchDetailContents.tsx
  src/components/lunch/ranking/LunchRankingReviews.tsx
  src/components/lunch/ranking/LunchRankings.tsx
  src/components/lunch/review/LunchReview.tsx
  src/components/lunch/review/LunchReviewPhotos.tsx
  src/components/lunch/review/LunchReviews.tsx
  src/components/lunch/review/LunchReviewsByRanking.tsx
  src/components/lunch/review/LunchReviewsByRest.tsx
  src/components/lunch/roulette/LunchRouletteBg.tsx
  src/components/lunch/roulette/LunchRouletteLockBtn.tsx
  src/components/lunch/roulette/LunchRoulettePushBtn.tsx
  src/constants/home/homeTexts.ts
  src/constants/lunch/index.ts
  src/pages/api/lunch/lunchRequests.ts
  src/pages/index.tsx
  src/pages/login/index.tsx
  src/pages/lunch/roulette.tsx
  src/stores/useBuildingStore.ts
  src/stores/useIdStore.ts
  src/stores/useReviewStore.ts
  src/stores/useRouletteStore.ts
  src/stores/useSaveStore.ts
  src/styles/font.ts
  src/styles/theme.ts
  src/types/common/response.ts
  src/types/lunch/api.ts
  src/types/lunch/reviewList.ts
  src/types/lunch/roulette.ts
Labels: 💎 완료

#147 fix: build error 수정
  src/stores/useSaveStore.ts
  src/types/common/response.ts
Labels: 🐞 버그
